version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
    groups:
      minor:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: /tools/lint
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
    groups:
      lint-tools:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "ci"
    labels:
      - ci
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
